env:
  global:
    - CC_TEST_REPORTER_ID=9af35b1465ab31d657e9bd4f88a135937be26420ad0ee220e25b8feef038b250
language: node_js
node_js:
  - "10"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run test:coverage
after_script:
  # Format server coverage
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.server.json server/coverage/lcov.info
  # Sum coverage parts into coverage/codeclimate.json
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 1
  # Upload coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
